# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # leave blank to use full name
first_name: Sreenivas
middle_name: 
last_name: Raguraman
contact_note: >
  Feel free to reach out via email for research inquiries or collaboration opportunities.
description: >
  I am an experimental materials scientist focused on the development and characterization of advanced alloys, particularly biodegradable magnesium alloys for biomedical and structural applications. My research integrates thermomechanical processing, corrosion testing, and advanced microscopy techniques to bridge fundamental materials science with real-world applications.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  #Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: materials science, biodegradable alloys, magnesium alloys, corrosion, atom probe tomography, experimental metallurgy
lang: en
icon: ⚛️

url: https://sreenivas-raguraman.github.io
baseurl: # leave blank
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light:
repo_theme_dark:
repo_trophies:
  enabled: false

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: false
posts_in_search: false
bib_search: true

max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: true
serve_schema_org: true
og_image:

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog (Disabled)
# -----------------------------------------------------------------------------

#blog_name:
#blog_description:
#permalink:
#lsi: false

#pagination:
#  enabled: false

#related_blog_posts:
#  enabled: false

#giscus:
# (commented out)

#disqus_shortname:

#external_sources:

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
  publications:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_projects", "_publications"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock

keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
  - jemoji
  - jekyll-scholar

# -----------------------------------------------------------------------------
# Scholar (for publications)
# -----------------------------------------------------------------------------

scholar:
  last_name: [Raguraman]
  first_name: [Sreenivas]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_thumbnails: true
max_author_limit: 3
more_authors_animation_delay: 10

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_darkmode: true
enable_math: true
enable_masonry: true
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
enable_navbar_social: true
enable_video_embedding: false

# -----------------------------------------------------------------------------
# Third Party Libraries
# -----------------------------------------------------------------------------

third_party_libraries: {}


# -----------------------------------------------------------------------------
# Responsive Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true

lazy_loading_images: true
